# Generated by Django 4.1.2 on 2023-10-19 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crime_records",
            old_name="ID",
            new_name="Row_ID",
        ),
    ]
