# Generated by Django 4.1.2 on 2023-10-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_rename_id_crime_records_row_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastCrimeRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Row_ID", models.IntegerField(db_index=True, unique=True)),
                ("Case_Number", models.CharField(max_length=10, unique=True)),
                ("Date", models.CharField(max_length=100)),
                ("Block", models.CharField(max_length=100)),
                ("IUCR", models.CharField(max_length=10)),
                ("Primary_Type", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=50)),
                ("Location_Description", models.CharField(max_length=500)),
                ("Arrest", models.BooleanField()),
                ("Domestic", models.BooleanField()),
                ("Beat", models.FloatField(max_length=10)),
                ("District", models.FloatField(max_length=10)),
                ("Ward", models.FloatField(max_length=10)),
                ("Community_Area", models.FloatField(max_length=10)),
                ("FBI_Code", models.CharField(max_length=10)),
                ("Updated_On", models.CharField(max_length=100)),
                ("Location", models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name="Crime_records",
        ),
    ]
