# Generated by Django 4.1.2 on 2023-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_pastcrimerecords1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastcrimerecords1",
            name="Case_Number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="pastcrimerecords1",
            name="Row_ID",
            field=models.IntegerField(db_index=True),
        ),
    ]
