# Generated by Django 4.1.2 on 2023-10-19 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0005_alter_pastcrimerecords1_case_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PastCrimeRecords1",
        ),
    ]
