# Generated by Django 4.1.2 on 2023-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0006_delete_pastcrimerecords1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pastcrimerecords",
            name="Location",
        ),
        migrations.AddField(
            model_name="pastcrimerecords",
            name="Latitude",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pastcrimerecords",
            name="Longitude",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
