# Generated by Django 4.1.2 on 2023-10-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0007_remove_pastcrimerecords_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastcrimerecords",
            name="Latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pastcrimerecords",
            name="Longitude",
            field=models.FloatField(),
        ),
    ]
